# Generated by Django 4.0 on 2021-12-12 10:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_card_id_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_id_img',
            field=models.ImageField(default='defualt-profile_LCrqeVq.jpg', upload_to=accounts.models.User.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='commercial_record_img',
            field=models.ImageField(default='defualt-profile_LCrqeVq.jpg', upload_to=accounts.models.User.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='defualt-profile_LCrqeVq.jpg', upload_to=accounts.models.User.upload_to),
        ),
    ]
